num_classes = 43
dataest_type = 'GTSRB'
poison_dataest_type = 'PoisonLabelGTSRB'
# dataset_mean = (0.3403, 0.3121, 0.3214)
# dataset_std = (0.2724, 0.2608, 0.2669)

max_epochs = 50

trainer = dict(
    type='AntiKDTrainer',
    teacher=dict(network=dict(arch='cifar',
                              type='resnet34',
                              num_classes=num_classes),
                 optimizer=dict(type='SGD',
                                lr=0.2,
                                momentum=0.9,
                                weight_decay=5e-4),
                 scheduler=dict(type='CosineAnnealingLR', T_max=max_epochs),
                 lambda_t=0.1,
                 lambda_mask=1e-4,
                 trainable_when_training_trigger=False),
    students=dict(
        resnet18=dict(network=dict(arch='cifar',
                                   type='resnet18',
                                   num_classes=num_classes),
                      optimizer=dict(type='SGD',
                                     lr=0.2,
                                     momentum=0.9,
                                     weight_decay=5e-4),
                      scheduler=dict(type='CosineAnnealingLR',
                                     T_max=max_epochs),
                      lambda_t=1e-2,
                      lambda_mask=1e-4,
                      trainable_when_training_trigger=False),
        vgg16=dict(network=dict(arch='cifar',
                                type='vgg16',
                                num_classes=num_classes),
                   optimizer=dict(type='SGD',
                                  lr=0.2,
                                  momentum=0.9,
                                  weight_decay=5e-4),
                   scheduler=dict(type='CosineAnnealingLR', T_max=max_epochs),
                   lambda_t=1e-2,
                   lambda_mask=1e-4,
                   trainable_when_training_trigger=False),
        mobilenet_v2=dict(network=dict(arch='cifar',
                                       type='mobilenet_v2',
                                       num_classes=num_classes),
                          optimizer=dict(type='SGD',
                                         lr=0.2,
                                         momentum=0.9,
                                         weight_decay=5e-4),
                          scheduler=dict(type='CosineAnnealingLR',
                                         T_max=max_epochs),
                          lambda_t=1e-2,
                          lambda_mask=1e-4,
                          trainable_when_training_trigger=False),
    ),
    trigger=dict(network=dict(arch='trigger', type='trigger', size=32),
                 optimizer=dict(type='Adam', lr=1e-2),
                 mask_clip_range=(0., 1.),
                 trigger_clip_range=(-1., 1.),
                 mask_penalty_norm=2),
    clean_train_dataloader=dict(dataset=dict(
        type=dataest_type,
        root='data',
        split='train',
        download=True,
        transform=[dict(type='Resize', size=(32, 32)),
                   dict(type='ToTensor')]),
                                batch_size=128,
                                num_workers=4,
                                pin_memory=True,
                                shuffle=True),
    clean_test_dataloader=dict(dataset=dict(
        type=dataest_type,
        root='data',
        split='test',
        download=True,
        transform=[dict(type='Resize', size=(32, 32)),
                   dict(type='ToTensor')]),
                               batch_size=128,
                               num_workers=4,
                               pin_memory=True),
    poison_train_dataloader=dict(dataset=dict(
        type=poison_dataest_type,
        poison_label=1,
        root='data',
        split='train',
        download=True,
        transform=[dict(type='Resize', size=(32, 32)),
                   dict(type='ToTensor')]),
                                 batch_size=128,
                                 num_workers=4,
                                 pin_memory=True,
                                 shuffle=True),
    poison_test_dataloader=dict(dataset=dict(
        type=poison_dataest_type,
        poison_label=1,
        root='data',
        split='test',
        download=True,
        transform=[dict(type='Resize', size=(32, 32)),
                   dict(type='ToTensor')]),
                                batch_size=128,
                                num_workers=4,
                                pin_memory=True),
    epochs=max_epochs,
    save_interval=5,
    temperature=1.0,
    alpha=1.0,
    device='cuda')
